import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Check, Clock, FileSpreadsheet, Lock, Mail, ShieldCheck, Sparkles, Wrench, XCircle } from 'lucide-react';
import './styles.css';

type PackageKey = 'quick-fix' | 'spreadsheet-cleanup' | 'dashboard-repair' | 'starter-build';

const intakeUrl = import.meta.env.VITE_INTAKE_FORM_URL || import.meta.env.PUBLIC_INTAKE_FORM_URL || 'mailto:hello@thomas-jenkins.net?subject=Spreadsheet%20project';

const services = [
  { icon: Wrench, title: 'Fix an Existing Spreadsheet', items: ['Broken formulas', 'VLOOKUP/XLOOKUP/INDEX-MATCH/FILTER/QUERY', 'SUMIFS/COUNTIFS issues', 'Dashboard repair', 'Messy workbook cleanup', 'Broken charts, pivots, filters, and summaries'] },
  { icon: FileSpreadsheet, title: 'Build a New Tracker or Dashboard', items: ['KPI dashboards', 'Sales, lead, recruiting, and staffing trackers', 'Inventory and project trackers', 'Real estate deal trackers', 'Operations dashboards', 'Weekly reporting templates'] },
  { icon: Sparkles, title: 'Add Light Automation', items: ['Google Forms to Sheets workflows', 'Auto timestamps and archive buttons', 'Status dropdowns and checkboxes', 'Email alerts', 'Simple Google Apps Script automation', 'Recurring report templates'] },
];

const packages = [
  { key: 'quick-fix', name: 'Quick Fix', price: '$49', description: 'Best for one specific issue such as a formula, lookup, filter, chart, formatting issue, or small broken section.' },
  { key: 'spreadsheet-cleanup', name: 'Spreadsheet Cleanup', price: '$99', description: 'Best for cleaning and improving an existing workbook, tracker, or report that has become messy, confusing, or hard to maintain.' },
  { key: 'dashboard-repair', name: 'Dashboard Repair', price: '$149', description: 'Best for fixing or improving an existing dashboard, KPI report, pivot summary, or reporting file.' },
  { key: 'starter-build', name: 'Starter Tracker or Dashboard Build', price: '$199', description: 'Best for a simple new tracker, reporting template, or dashboard built from scratch.' },
];

function Header() { return <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><a href="/" className="flex items-center gap-2 font-bold text-slate-950"><FileSpreadsheet className="h-6 w-6 text-blue-700"/>Spreadsheet Fixer</a><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="/#services">Services</a><a href="/#pricing">Pricing</a><a href="/#guarantee">Guarantee</a><a href="/#process">How It Works</a><a href="/#faq">FAQ</a></nav><a className="btn btn-primary" href="/#pricing">Get Started</a></div></header> }
function Footer() { return <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-slate-600 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><p>© {new Date().getFullYear()} thomas-jenkins.net. Spreadsheet repair and custom reporting tools.</p><div className="flex gap-5"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:hello@thomas-jenkins.net">Contact</a><a href="https://thomas-jenkins.net">thomas-jenkins.net</a></div></div></footer> }
function Hero(){return <section className="relative overflow-hidden bg-[radial-gradient(circle_at_top_left,#dbeafe,transparent_35%),linear-gradient(135deg,#f8fafc,#eef2ff)]"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div><p className="eyebrow"><ShieldCheck className="h-4 w-4"/>Secure Stripe checkout · Google Sheets & Excel</p><h1>Fix or build the spreadsheet your business actually needs.</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-700">I fix broken Google Sheets and Excel files, clean up messy trackers, repair dashboards, and build custom reporting tools for small businesses.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="btn btn-primary btn-lg" href="/#pricing">Fix My Spreadsheet <ArrowRight className="h-4 w-4"/></a><a className="btn btn-secondary btn-lg" href="/#pricing">Build a Tracker/Dashboard</a></div><p className="mt-4 text-sm font-medium text-slate-600">Most fixes: $49–$199. 24-hour guarantee on agreed-scope repair work.</p></div><div className="card p-6 shadow-2xl"><div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-sm text-blue-200">Typical spreadsheet rescue</p><div className="mt-5 space-y-3">{['Broken lookup formulas fixed','Summary dashboard refreshed','Manual report converted to template','Client walkthrough delivered'].map(x=><div className="flex items-center gap-3" key={x}><Check className="h-5 w-5 text-emerald-400"/><span>{x}</span></div>)}</div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-blue-50 p-4"><b>24h</b><p>repair guarantee</p></div><div className="rounded-xl bg-emerald-50 p-4"><b>Stripe</b><p>secure payment</p></div></div></div></div></section>}
function ServicePathCards(){return <section id="services" className="section"><div className="section-head"><p className="eyebrow">Services</p><h2>Three practical ways to get your spreadsheet working again.</h2><p>Broken formulas, messy trackers, manual reports, confusing dashboards, and spreadsheet tools that no longer work the way they should can slow down every part of a small business.</p></div><div className="grid gap-5 md:grid-cols-3">{services.map(s=><article className="card p-6" key={s.title}><s.icon className="h-9 w-9 text-blue-700"/><h3>{s.title}</h3><ul className="mt-4 space-y-2 text-sm text-slate-600">{s.items.map(i=><li className="flex gap-2" key={i}><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/>{i}</li>)}</ul></article>)}</div></section>}
async function startCheckout(packageKey: PackageKey){const res=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packageKey})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.url) throw new Error(data.error||'Unable to start checkout.'); window.location.href=data.url;}
function PricingCards(){const [busy,setBusy]=React.useState<string>(); const [err,setErr]=React.useState(''); return <section id="pricing" className="section bg-slate-50"><div className="section-head"><p className="eyebrow">Pricing</p><h2>Start with a clear package and secure checkout.</h2><p>The browser only sends the selected package key. Prices are validated on the server before Stripe Checkout is created.</p></div>{err&&<p className="mx-auto mb-4 max-w-2xl rounded-xl bg-red-50 p-3 text-red-700">{err}</p>}<div className="grid gap-5 lg:grid-cols-5">{packages.map(p=><article className="card flex flex-col p-6" key={p.key}><h3>{p.name}</h3><p className="mt-3 text-4xl font-extrabold text-slate-950">{p.price}</p><p className="mt-4 flex-1 text-sm text-slate-600">{p.description}</p><button className="btn btn-primary mt-6 w-full" disabled={!!busy} onClick={async()=>{setBusy(p.key);setErr('');try{await startCheckout(p.key as PackageKey)}catch(e){setErr(e instanceof Error?e.message:'Checkout failed.');setBusy(undefined)}}}>{busy===p.key?'Starting…':'Pay & Start'}</button></article>)}<article className="card flex flex-col border-blue-200 bg-blue-950 p-6 text-white"><h3>Custom Business Tool</h3><p className="mt-3 text-4xl font-extrabold">Quote</p><p className="mt-4 flex-1 text-sm text-blue-100">Best for larger dashboards, multi-tab trackers, automation workflows, or spreadsheet tools built around a business process.</p><a className="btn mt-6 w-full bg-white text-blue-950 hover:bg-blue-50" href={intakeUrl}>Request Quote</a></article></div></section>}
function Guarantee(){return <section id="guarantee" className="section"><div className="rounded-3xl bg-gradient-to-br from-blue-950 to-slate-900 p-8 text-white shadow-xl md:p-12"><Clock className="h-10 w-10 text-emerald-300"/><h2 className="mt-4">24-Hour Fix Guarantee</h2><p className="mt-4 text-lg text-blue-50">For agreed-scope spreadsheet repair work, once I have access to the file and we confirm the issue, I’ll fix it within 24 hours or refund your payment.</p><p className="mt-4 text-sm text-blue-100">External data sources, APIs, third-party systems, missing access, client response delays, and scope changes are excluded from the 24-hour guarantee. New builds and custom projects receive a clear timeline before work begins.</p></div></section>}
function Process(){return <section id="process" className="section bg-white"><div className="section-head"><p className="eyebrow">How it works</p><h2>A simple path from messy spreadsheet to usable business tool.</h2></div><div className="grid gap-4 md:grid-cols-5">{['Send the file, screenshot, or idea','I confirm scope and price','You pay securely','I fix it or build it','You get a short walkthrough'].map((s,i)=><div className="card p-5" key={s}><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-800">{i+1}</div><p className="font-semibold text-slate-900">{s}</p></div>)}</div></section>}
function FAQ(){const qs=[['Do you work with Excel and Google Sheets?','Yes. I can repair and build in both Microsoft Excel and Google Sheets.'],['Can you build a new tracker from scratch?','Yes. Starter builds cover simple trackers, templates, and dashboards; larger tools are quoted.'],['What does the 24-hour guarantee include?','Agreed-scope repair work after access is provided and the issue is confirmed.'],['What is excluded from the guarantee?','External data sources, APIs, third-party systems, missing access, client delays, and scope changes.'],['Can you work with confidential business data?','Yes, but please avoid sending highly sensitive data unless we agree on handling requirements in advance.'],['Do you support external APIs?','Light API or third-party integrations may be possible as custom quoted work, but they are excluded from the 24-hour repair guarantee.'],['What happens after I pay?','Stripe redirects you to a success page with an intake link. You will receive confirmation and next steps by email.'],['Can I request a custom dashboard?','Yes. Use the quote or intake CTA for dashboards tied to a larger business process.']];return <section id="faq" className="section bg-slate-50"><div className="section-head"><p className="eyebrow">FAQ</p><h2>Common questions before you start.</h2></div><div className="mx-auto grid max-w-4xl gap-4">{qs.map(([q,a])=><details className="card p-5" key={q}><summary className="cursor-pointer font-semibold text-slate-950">{q}</summary><p className="mt-3 text-slate-600">{a}</p></details>)}</div></section>}
function CTASection(){return <section className="section"><div className="card flex flex-col items-start justify-between gap-5 bg-white p-8 md:flex-row md:items-center"><div><h2 className="text-3xl">Ready to make your spreadsheet reliable?</h2><p className="mt-2 text-slate-600">Choose a package or request a custom quote for a larger dashboard or workflow.</p></div><a href="/#pricing" className="btn btn-primary btn-lg">Get Started</a></div></section>}
function Home(){return <><Hero/><ServicePathCards/><PricingCards/><Guarantee/><Process/><FAQ/><CTASection/></>}
function Success(){return <main className="section min-h-[60vh]"><div className="card mx-auto max-w-2xl p-8 text-center"><Check className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="mt-4 text-4xl">Payment received</h1><p className="mt-4 text-slate-600">Thanks for your order. Please check your email for Stripe confirmation and submit your project details so work can begin.</p><a className="btn btn-primary btn-lg mt-8" href={intakeUrl}>Submit project details</a></div></main>}
function Cancel(){return <main className="section min-h-[60vh]"><div className="card mx-auto max-w-2xl p-8 text-center"><XCircle className="mx-auto h-12 w-12 text-amber-500"/><h1 className="mt-4 text-4xl">Checkout canceled</h1><p className="mt-4 text-slate-600">No payment was completed. You can return to pricing whenever you are ready.</p><a className="btn btn-primary btn-lg mt-8" href="/#pricing">Back to pricing</a></div></main>}
function Legal({type}:{type:'Privacy'|'Terms'}){return <main className="section prose"><h1>{type} Policy</h1><p><strong>Draft starter language — review with qualified counsel before publishing.</strong></p><p>This {type.toLowerCase()} page explains basic expectations for using Spreadsheet Fixer services at thomas-jenkins.net. Customers should not submit highly sensitive personal, financial, medical, or regulated data unless handling requirements are agreed in advance.</p><p>Project files, screenshots, and descriptions are used to evaluate, repair, or build spreadsheet tools. Payment is processed by Stripe-hosted checkout. Production secrets are stored in Cloudflare Pages variables and are not committed to this repository.</p><p>For questions, contact <a href="mailto:hello@thomas-jenkins.net">hello@thomas-jenkins.net</a>.</p></main>}
function App(){const path=window.location.pathname;let page=<Home/>; if(path==='/success') page=<Success/>; if(path==='/cancel') page=<Cancel/>; if(path==='/privacy') page=<Legal type="Privacy"/>; if(path==='/terms') page=<Legal type="Terms"/>; return <><Header/>{page}<Footer/></>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
